apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: credit-fraud
  namespace: seldon
spec:
  protocol: tensorflow
  name: credit-fraud
  predictors:
  - graph:
      implementation: TENSORFLOW_SERVER
      modelUri: gs://rfdickerson-credit-fraud-model/credit-fraud
      name: classifier
    name: default
    replicas: 1